name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  create:
    tags: ['v*.*.*']  # Dispara también en tags semánticos

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          jquiej/proyecto-so-2:latest
          jquiej/proyecto-so-2:${{ github.sha }}

  test:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run PHPUnit
      run: vendor/bin/phpunit
    - name: Static analysis
      run: vendor/bin/phpstan analyse

  deploy:
    needs: [build-and-push, test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    - name: Deploy to Kubernetes
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        echo "$KUBE_CONFIG_DATA" | base64 -d > kubeconfig
        kubectl --kubeconfig=kubeconfig apply -f k8s/
    - name: Notify Slack
      if: always()
      uses: Ilshidur/action-slack@v2
      with:
        status: ${{ job.status }}
        fields: repo,message,commit
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
